# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1378378901);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1378379116);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.slowStartup.averageTime", 917);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20130814063812");
user_pref("browser.startup.homepage_override.mstone", "23.0.1");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1378465301270");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1378378901269");
user_pref("datareporting.sessions.current.activeTicks", 12);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 851);
user_pref("datareporting.sessions.current.main", 226);
user_pref("datareporting.sessions.current.sessionRestored", 889);
user_pref("datareporting.sessions.current.startTime", "1378379263780");
user_pref("datareporting.sessions.current.totalTime", 58);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.0", "{\"s\":1378378901032,\"a\":2,\"t\":6,\"c\":true,\"m\":48,\"fp\":858,\"sr\":936}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1378378909705,\"a\":17,\"t\":82,\"c\":true,\"m\":78,\"fp\":610,\"sr\":626}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1378114443735,\"a\":21,\"t\":264677,\"c\":true,\"m\":264549698,\"fp\":264550135,\"sr\":264552934}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1378379121220,\"a\":21,\"t\":103,\"c\":true,\"m\":273,\"fp\":923,\"sr\":960}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1378379224475,\"a\":8,\"t\":39,\"c\":true,\"m\":248,\"fp\":821,\"sr\":857}");
user_pref("dom.mozApps.used", true);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"firebug@software.joehewitt.com\":{\"version\":\"1.12.1\",\"type\":\"extension\",\"descriptor\":\"D:\\\\git\\\\my\\\\selenium-test\\\\Selenium-Test\\\\Selenium-Profiles\\\\Firefox\\\\extensions\\\\firebug@software.joehewitt.com.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "skipcerterror%40foudil.fr:0.3.4,FireXPath%40pierre.tholence.com:0.9.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:23.0.1");
user_pref("extensions.fbmlconsole.customfiltertypes", "#cmlchecknoticeui-info#cmlchecknoticeui-warning#cmlchecknoticeui-notice");
user_pref("extensions.fbmlconsole.logConfigurations", "{\"default local log\":{\"isLocal\":true,\"path\":\"C:\\\\Program Files\\\\MarkLogic\\\\Data\\\\Logs\\\\ErrorLog.txt\"},\"default remote log\":{\"isLocal\":false,\"path\":\"http://localhost:8001/get-error-log.xqy?filename=ErrorLog.txt\",\"user\":\"admin\",\"pass\":\"admin\"}}");
user_pref("extensions.fbmlconsole.selectedLogConfig", "");
user_pref("extensions.fbmlconsole.togglestatus", "level-custom#cmltoggleCustom");
user_pref("extensions.firebug.console.enableSites", true);
user_pref("extensions.firebug.currentVersion", "1.12.1");
user_pref("extensions.firebug.defaultPanelName", "firepath");
user_pref("extensions.firebug.toolbarCustomizationDone", true);
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"{BBDA0591-3099-440a-AA10-41764D9DB4DB}\":{\"descriptor\":\"C:\\\\ProgramData\\\\Symantec\\\\Symantec Endpoint Protection\\\\12.1.2100.2093.105\\\\Data\\\\IPSFFPlgn\",\"mtime\":1378114031051,\"rdfTime\":1378114031051}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1378378932823,\"rdfTime\":1378378932792}}},{\"name\":\"app-profile\",\"addons\":{\"firebug@software.joehewitt.com\":{\"descriptor\":\"D:\\\\git\\\\my\\\\selenium-test\\\\Selenium-Test\\\\Selenium-Profiles\\\\Firefox\\\\extensions\\\\firebug@software.joehewitt.com.xpi\",\"mtime\":1378379095301},\"skipcerterror@foudil.fr\":{\"descriptor\":\"D:\\\\git\\\\my\\\\selenium-test\\\\Selenium-Test\\\\Selenium-Profiles\\\\Firefox\\\\extensions\\\\skipcerterror@foudil.fr.xpi\",\"mtime\":1378378993548},\"FireXPath@pierre.tholence.com\":{\"descriptor\":\"D:\\\\git\\\\my\\\\selenium-test\\\\Selenium-Test\\\\Selenium-Profiles\\\\Firefox\\\\extensions\\\\FireXPath@pierre.tholence.com.xpi\",\"mtime\":1378379264102}}}]");
user_pref("extensions.lastAppVersion", "23.0.1");
user_pref("extensions.lastPlatformVersion", "23.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.sce.bypass_domain_mismatch", true);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/xpath");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20130814063812");
user_pref("gecko.mstone", "23.0.1");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("gfx.direct3d.prefer_10_1", true);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1378379264);
user_pref("toolkit.telemetry.previousBuildID", "20130814063812");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1380970904);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
